<?php

  // クロスオリジンを許可する
  header( "Access-Control-Allow-Origin:*" );
  // ヘッダーにコンテンツの種類を設定する
  header( "Content-Type:application/json" );

  $products = [
    "photo" => [
      [
        "id" => "01",
        "year" => "2018",
        "img" => "2",
        "date" => "'17.9.10",
        "place" => "Nara park, Nara",
        "alt" => "奈良公園",
        "vertical" => false,
      ],
      [
        "id" => "02",
        "year" => "2018",
        "img" => "3",
        "date" => "'18.3.27",
        "place" => "Arashiyama, Kyoto",
        "alt" => "嵐山",
        "vertical" => false,
      ],
      [
        "id" => "03",
        "year" => "2018",
        "img" => "2",
        "date" => "'18.3.27",
        "place" => "Toji, Kyoto",
        "alt" => "東寺",
        "vertical" => true,
      ],
      [
        "id" => "04",
        "year" => "2018",
        "img" => "2",
        "date" => "'18.4.3",
        "place" => "Nara",
        "alt" => "奈良",
        "vertical" => false,
      ],
      [
        "id" => "05",
        "year" => "2018",
        "img" => "5",
        "date" => "'18.7.29",
        "place" => "Kamikochi, Nagano",
        "alt" => "上高地",
        "vertical" => false,
      ],
      [
        "id" => "06",
        "year" => "2018",
        "img" => "6",
        "date" => "'18.8.31",
        "place" => "Toji, Kyoto",
        "alt" => "東寺",
        "vertical" => false,
      ],
      [
        "id" => "07",
        "year" => "2018",
        "img" => "4",
        "date" => "'18.11.24",
        "place" => "Hogonin, Kyoto",
        "alt" => "宝厳院",
        "vertical" => false,
      ],
      [
        "id" => "08",
        "year" => "2018",
        "img" => "1",
        "date" => "'18.11.24",
        "place" => "Toji, Kyoto",
        "alt" => "東寺",
        "vertical" => false,
      ],
      [
        "id" => "09",
        "year" => "2019",
        "img" => "1",
        "date" => "'19.3.5",
        "place" => "Kitanotemmangu, Kyoto",
        "alt" => "北野天満宮",
        "vertical" => false,
      ],
      [
        "id" => "10",
        "year" => "2019",
        "img" => "5",
        "date" => "'19.4.5",
        "place" => "Byodoin, Kyoto",
        "alt" => "平等院",
        "vertical" => false,
      ],
      [
        "id" => "11",
        "year" => "2019",
        "img" => "3",
        "date" => "'19.4.5",
        "place" => "Nijojo, Kyoto",
        "alt" => "二条城",
        "vertical" => false,
      ],
      [
        "id" => "12",
        "year" => "2019",
        "img" => "5",
        "date" => "'19.4.13",
        "place" => "Sanzenin, Kyoto",
        "alt" => "三千院",
        "vertical" => true,
      ],
      [
        "id" => "13",
        "year" => "2019",
        "img" => "2",
        "date" => "'19.5.17",
        "place" => "My mother's roses",
        "alt" => "母の薔薇",
        "vertical" => false,
      ],
      [
        "id" => "14",
        "year" => "2019",
        "img" => "8",
        "date" => "'19.6.3",
        "place" => "Umeda, Osaka",
        "alt" => "梅田スナップ",
        "vertical" => false,
      ],
      [
        "id" => "15",
        "year" => "2019",
        "img" => "3",
        "date" => "'19.8.10",
        "place" => "なにわ淀川花火大会, Osaka",
        "alt" => "なにわ淀川花火大会",
        "vertical" => false,
      ],
      [
        "id" => "16",
        "year" => "2019",
        "img" => "5",
        "date" => "'19.10.19",
        "place" => "Yanagawa, Fukuoka",
        "alt" => "柳川",
        "vertical" => false,
      ],
      [
        "id" => "17",
        "year" => "2019",
        "img" => "4",
        "date" => "'19.10.19",
        "place" => "Birthplace of Hakushu Kitahara, Fukuoka",
        "alt" => "北原白秋生家",
        "vertical" => true,
      ],
      [
        "id" => "18",
        "year" => "2019",
        "img" => "5",
        "date" => "'19.10.20",
        "place" => "Nagasaki",
        "alt" => "長崎",
        "vertical" => false,
      ],
      [
        "id" => "19",
        "year" => "2019",
        "img" => "6",
        "date" => "'19.10.21",
        "place" => "Mojiko, Fukuoka",
        "alt" => "門司港",
        "vertical" => false,
      ],
      [
        "id" => "20",
        "year" => "2019",
        "img" => "6",
        "date" => "'19.11.23",
        "place" => "Minoo, Osaka",
        "alt" => "箕面"
      ],
      [
        "id" => "21",
        "year" => "2019",
        "img" => "4",
        "date" => "'19.11.26",
        "place" => "Toji, Kyoto",
        "alt" => "東寺",
        "vertical" => true,
      ],
      [
        "id" => "22",
        "year" => "2020",
        "img" => "3",
        "date" => "'20.3.20",
        "place" => "Imperial theatre, Tokyo",
        "alt" => "帝国劇場",
        "vertical" => false,
      ],
      [
        "id" => "23",
        "year" => "2020",
        "img" => "5",
        "date" => "'20.9.20",
        "place" => "Kurashiki City, Okayama",
        "alt" => "倉敷市",
        "vertical" => false,
      ],
      [
        "id" => "24",
        "year" => "2020",
        "img" => "5",
        "date" => "'20.11.21",
        "place" => "Imagumakannonji, Sennyuji, Kyoto",
        "alt" => "今隈観音寺、泉涌寺",
        "vertical" => false,
      ],
      [
        "id" => "25",
        "year" => "2020",
        "img" => "3",
        "date" => "'20.11.28",
        "place" => "Eikando, Kyoto",
        "alt" => "永観堂",
        "vertical" => false,
      ],
      [
        "id" => "26",
        "year" => "2020",
        "img" => "7",
        "date" => "'20.12.25",
        "place" => "Huistenbosch, Nagasaki",
        "alt" => "ハウステンボス",
        "vertical" => false,
      ],
      [
        "id" => "27",
        "year" => "2021",
        "img" => "9",
        "date" => "'21.3.29",
        "place" => "Ohmihachiman City, Shiga",
        "alt" => "近江八幡市",
        "vertical" => false,
      ],
      [
        "id" => "28",
        "year" => "2021",
        "img" => "6",
        "date" => "'21.3.29",
        "place" => "Heianjingu, Kyoto",
        "alt" => "平安神宮",
        "vertical" => false,
      ],
      [
        "id" => "29",
        "year" => "2021",
        "img" => "12",
        "img" => "3",
        "date" => "'21.3.30",
        "place" => "Kiyomizudera, Kyoto",
        "alt" => "清水寺",
        "vertical" => false,
      ],
      [
        "id" => "30",
        "year" => "2021",
        "img" => "5",
        "date" => "'21.3.31",
        "place" => "Yamatosaidaiji, Nara",
        "alt" => "大和西大寺",
        "vertical" => false,
      ],
      [
        "id" => "31",
        "year" => "2021",
        "img" => "3",
        "date" => "'21.4.3",
        "place" => "Yakushiji, Nara",
        "alt" => "薬師寺",
        "vertical" => false,
      ],
      [
        "id" => "32",
        "year" => "2021",
        "img" => "10",
        "date" => "'21.6.6",
        "place" => "Yokokuji, Kyoto",
        "alt" => "楊谷寺",
        "vertical" => true,
      ],
      [
        "id" => "33",
        "year" => "2021",
        "img" => "4",
        "date" => "'21.7.11",
        "place" => "Yasaka Koshindo",
        "alt" => "八坂庚申堂",
        "vertical" => false,
      ],
      [
        "id" => "34",
        "year" => "2021",
        "img" => "3",
        "date" => "'21.7.11",
        "place" => "DORUMIRU Yasaka no Tou,Kyoto",
        "alt" => "ドルミール 八坂の塔",
        "vertical" => false,
      ],
      [
        "id" => "35",
        "year" => "2021",
        "img" => "5",
        "date" => "'21.9.21",
        "place" => "Cluster amaryllis flower field, Kameoka",
        "alt" => "亀岡 彼岸花の里",
        "vertical" => true,
      ],
      [
        "id" => "36",
        "year" => "2021",
        "img" => "1",
        "date" => "'21.9.21",
        "place" => "Anao Temple, Kyoto",
        "alt" => "穴太寺",
        "vertical" => false,
      ],
      [
        "id" => "37",
        "year" => "2021",
        "img" => "9",
        "date" => "'21.11.7",
        "place" => "Mettya jimoto no yama",
        "alt" => "めっちゃ地元の山",
        "vertical" => true,
      ],
      [
        "id" => "38",
        "year" => "2021",
        "img" => "8",
        "date" => "'21.11.27",
        "place" => "Nara park, Nara",
        "alt" => "奈良公園",
        "vertical" => true,
      ],
      [
        "id" => "39",
        "year" => "2021",
        "img" => "5",
        "date" => "'21.11.27",
        "place" => "Kasuga shrine, Nara",
        "alt" => "春日大社",
        "vertical" => false,
      ],
      [
        "id" => "40",
        "year" => "2021",
        "img" => "7",
        "date" => "'21.12.10",
        "place" => "Shinsaibashi, Osaka",
        "alt" => "光の饗宴 心斎橋",
        "vertical" => true,
      ],
      [
        "id" => "41",
        "year" => "2021",
        "img" => "7",
        "date" => "'21.12.11",
        "place" => "Minamiza, Pontocho, Kyoto",
        "alt" => "南座、先斗町",
        "vertical" => false,
      ],
      [
        "id" => "42",
        "year" => "2022",
        "img" => "3",
        "date" => "'22.3.3",
        "place" => "Hina dolls",
        "alt" => "雛人形",
        "vertical" => true,
      ],
      [
        "id" => "43",
        "year" => "2022",
        "img" => "4",
        "date" => "'22.3.26",
        "place" => "My mother's muscaris etc",
        "alt" => "母のムスカリとか",
        "vertical" => true,
      ],
      [
        "id" => "44",
        "year" => "2022",
        "img" => "10",
        "date" => "'22.3.26",
        "place" => "Suikatemmangu, Kyoto",
        "alt" => "水火天満宮",
        "vertical" => false,
      ],
      [
        "id" => "45",
        "year" => "2022",
        "img" => "2",
        "date" => "'22.3.26",
        "place" => "Heianjingu, Kyoto",
        "alt" => "平安神宮",
        "vertical" => false,
      ],
      [
        "id" => "46",
        "year" => "2022",
        "img" => "1",
        "date" => "'22.3.26",
        "place" => "Rikyuhachimangu, Kyoto",
        "alt" => "離宮八幡宮",
        "vertical" => false,
      ],
      [
        "id" => "47",
        "year" => "2022",
        "img" => "9",
        "date" => "'22.4.10",
        "place" => "Heianjingu Shinen, Nara",
        "alt" => "平安神宮 神苑",
        "vertical" => false,
      ],
      [
        "id" => "48",
        "year" => "2022",
        "img" => "4",
        "date" => "'22.4.30",
        "place" => "Manyoshokubuen, Nara",
        "alt" => "萬葉植物園",
        "vertical" => true,
      ],
      [
        "id" => "49",
        "year" => "2022",
        "img" => "2",
        "date" => "'22.4.30",
        "place" => "Manyoshokubuen, Nara",
        "alt" => "萬葉植物園",
        "vertical" => false,
      ],
      [
        "id" => "50",
        "year" => "2022",
        "img" => "9",
        "date" => "'22.4.30",
        "place" => "Manyoshokubuen, Approach to Kasuga-taisha, Nara",
        "alt" => "萬葉植物園、春日大社参道",
        "vertical" => false,
      ],
    ],
    "index" => [
      "https://manami-sato.github.io/philosophia/img/img_32_06.jpg",
      "https://manami-sato.github.io/philosophia/img/img_29_02.jpg",
      "https://manami-sato.github.io/philosophia/img/img_27_09.jpg",
      "https://manami-sato.github.io/philosophia/img/img_33_01.jpg"
    ],
  ];

  print json_encode($products);